version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: chatdb-checkpoint
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Matkhaula@123
      POSTGRES_DB: checkpoint
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatdb-agent
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    image: chatdb-agent:latest
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    networks:
      - chat-db

volumes:
  postgres_data:


networks:
  chat-db:
    driver: bridge
