version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: chatdb-checkpoint
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Matkhaula@123
      POSTGRES_DB: checkpoint
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data\
    networks:
      - chat-db

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatdb-agent
    image: chatdb-agent:latest
    depends_on:
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - chat-db

volumes:
  postgres_data:


networks:
  chat-db:
    driver: bridge
