services:
  postgres:
    image: postgres:16
    container_name: chatdb-checkpoint
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Matkhaula@123
      POSTGRES_DB: checkpoint
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d checkpoint" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - chat-db

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatdb-agent
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: chatdb-agent:latest
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    networks:
      - chat-db

volumes:
  postgres_data:
  redis_data:


networks:
  chat-db:
    driver: bridge
